bsp.c File Reference
bsp.c File Reference
Functions
void trimAdcSetGolbalVar (void)
void trimLdoSimoVadjSetGolbalVar (void)
void GPR_RmiErrCfg (bool en)
uint32_t GPR_RmiErrAddrGet (void)
__WEAK void pmuInit (void)
__WEAK void uniLogFlushOut (uint32_t flush_data)
__WEAK void uniLogForceOut (bool waitFifoOut)
void BSP_InitUartDriver (ARM_DRIVER_USART *drvHandler, ARM_POWER_STATE powerMode, uint32_t settings, uint32_t baudRate, ARM_USART_SignalEvent_t cb_event)
void BSP_DeinitUartDriver (ARM_DRIVER_USART *drvHandler)
void BSP_SetPrintUart (usart_port_t port)
char * ec_strnstr (const char *s, const char *find, size_t slen)
void setOSState (uint8_t state)
PLAT_CODE_IN_RAM uint8_t getOSState (void)
uint8_t * getBuildInfo (void)
uint8_t * getVersionInfo (void)
uint8_t * getDebugDVersion (void)
__attribute__ ((noinline))
void FlushUnilogOutput (uint32_t flush_data)
uint32_t GET_PMU_RAWFLASH_OFFSET (void)
bool pmuHasAtData (void)
void GPR_rmiErrDetectInit (void)
void BSP_CommonInit (void)
Variables
ARM_DRIVER_USART Driver_USART0
ARM_DRIVER_USART Driver_USART1
ARM_DRIVER_USART * UsartPrintHandle = NULL
ARM_DRIVER_USART * UsartUnilogHandle = NULL
ARM_DRIVER_USART * UsartAtCmdHandle = NULL
uint8_t chipIDInfuse = 0
Function Documentation
trimAdcSetGolbalVar()
void trimAdcSetGolbalVar (void)
Referenced by BSP_CommonInit().
trimLdoSimoVadjSetGolbalVar()
void trimLdoSimoVadjSetGolbalVar (void)
Referenced by BSP_CommonInit().
GPR_RmiErrCfg()
void GPR_RmiErrCfg (bool en)
GPR_RmiErrAddrGet()
uint32_t GPR_RmiErrAddrGet (void)
pmuInit()
__WEAK void pmuInit (void)
Referenced by BSP_CommonInit().
uniLogFlushOut()
__WEAK void uniLogFlushOut (uint32_t flush_data)
Referenced by doSleep1Presync().
uniLogForceOut()
__WEAK void uniLogForceOut (bool waitFifoOut)
Referenced by FlushUnilogOutput().
BSP_InitUartDriver()
void BSP_InitUartDriver (ARM_DRIVER_USART * drvHandler, ARM_POWER_STATE powerMode, uint32_t settings, uint32_t baudRate, ARM_USART_SignalEvent_t cb_event)
BSP_DeinitUartDriver()
void BSP_DeinitUartDriver (ARM_DRIVER_USART * drvHandler)
BSP_SetPrintUart()
void BSP_SetPrintUart (usart_port_t port)
ec_strnstr()
char* ec_strnstr (const char * s, const char * find, size_t slen)
setOSState()
void setOSState (uint8_t state)
getOSState()
PLAT_CODE_IN_RAM uint8_t getOSState (void)
Referenced by BSP_SavePlatConfigToRawFlash().
getBuildInfo()
uint8_t* getBuildInfo (void)
getVersionInfo()
uint8_t* getVersionInfo (void)
getDebugDVersion()
uint8_t* getDebugDVersion (void)
__attribute__()
__attribute__ ((noinline))
FlushUnilogOutput()
void FlushUnilogOutput (uint32_t flush_data)
GET_PMU_RAWFLASH_OFFSET()
uint32_t GET_PMU_RAWFLASH_OFFSET (void)
pmuHasAtData()
bool pmuHasAtData (void)
GPR_rmiErrDetectInit()
void GPR_rmiErrDetectInit (void)
Referenced by BSP_CommonInit(), and BSP_Init_SmallImg().
BSP_CommonInit()
void BSP_CommonInit (void)
Variable Documentation
Driver_USART0
ARM_DRIVER_USART Driver_USART0
Driver_USART1
ARM_DRIVER_USART Driver_USART1
UsartPrintHandle
ARM_DRIVER_USART* UsartPrintHandle = NULL
Referenced by BSP_SetPrintUart().
UsartUnilogHandle
ARM_DRIVER_USART* UsartUnilogHandle = NULL
Referenced by FlushUnilogOutput().
UsartAtCmdHandle
ARM_DRIVER_USART* UsartAtCmdHandle = NULL
chipIDInfuse
uint8_t chipIDInfuse = 0