ec_main.c File Reference
ec_main.c File Reference
Functions
void __PmCoreRegRestore (void)
void SystemFullImageInit (void)
void PhyPowerOnInit (UINT8 wakeupType)
void PhyEndWorkOnPadInt (void)
void PHY_PMU_WAKEUP_TYPE_SET (UINT8 wakeupType)
void slpManAonWdtFeed (void)
void main_entry (void)
void GPR_rmiErrDetectInit (void)
void PmuCheckHibTimerWkup ()
void BSP_Init_SmallImg (void)
void BSP_DeInit_SmallImg (void)
void BSP_Init_Slp1Presync (void)
bool pmuHasWakeupPending (void)
void doSleep1Presync (UINT8 wakeupType)
int ec_main (void)
Function Documentation
__PmCoreRegRestore()
void __PmCoreRegRestore (void)
SystemFullImageInit()
void SystemFullImageInit (void)
PhyPowerOnInit()
void PhyPowerOnInit (UINT8 wakeupType)
Referenced by doSleep1Presync().
PhyEndWorkOnPadInt()
void PhyEndWorkOnPadInt (void)
Referenced by doSleep1Presync().
PHY_PMU_WAKEUP_TYPE_SET()
void PHY_PMU_WAKEUP_TYPE_SET (UINT8 wakeupType)
slpManAonWdtFeed()
void slpManAonWdtFeed (void)
Referenced by doSleep1Presync().
main_entry()
void main_entry (void)
GPR_rmiErrDetectInit()
void GPR_rmiErrDetectInit (void)
Referenced by BSP_CommonInit(), and BSP_Init_SmallImg().
PmuCheckHibTimerWkup()
void PmuCheckHibTimerWkup ()
BSP_Init_SmallImg()
void BSP_Init_SmallImg (void)
BSP_DeInit_SmallImg()
void BSP_DeInit_SmallImg (void)
BSP_Init_Slp1Presync()
void BSP_Init_Slp1Presync (void)
Referenced by doSleep1Presync().
pmuHasWakeupPending()
bool pmuHasWakeupPending (void)
Referenced by doSleep1Presync().
doSleep1Presync()
void doSleep1Presync (UINT8 wakeupType)
ec_main()
int ec_main (void)