XIC Interface
XIC Interface
Driver API for XIC(External Interrupt controller)
Macros
#define NUM_XIC_MODULE (3U)
#define NUM_XIC0_INT (32U)
#define NUM_XIC1_INT (32U)
#define NUM_XIC2_INT (27U)
#define MAX_NUM_XIC_INT (32U)
Typedefs
typedef void(* ISRFunc_T) (void)
Functions
void IC_PowupInit (void)
Initialize the interrupt controller, including HW configuration and ISR initialization, called when POR or wakeup from Hibernate, in which the SRAM contents have been lost.
void IC_PowupSlp1Init (void)
for paging sleep1 init called when start sleep1 paging flow
void IC_Powoff (void)
DeInitialize the interrupt controller, including HW configuration and ISR initialization.
void XIC_SetVector (IRQn_Type IRQn, ISRFunc_T vector)
Sets an XIC interrupt vector in SRAM based interrupt vector table. Use this function to bind the XIC interrupt and application ISR.
void XIC_EnableIRQ (IRQn_Type IRQn)
Enables a device specific interrupt in the XIC interrupt controller.
void XIC_DisableIRQ (IRQn_Type IRQn)
Disables a device specific interrupt in the XIC interrupt controller.
void XIC_BackupIRQSetting (uint32_t *xic_mask, uint32_t *xic_clrovf)
backup the interrupt mask setting before sleep
void XIC_RestoreIRQSetting (uint32_t *xic_mask, uint32_t *xic_clrovf)
restore the interrupt mask setting after sleep
void XIC_SetPendingIRQ (IRQn_Type IRQn)
Sets the pending bit of a device specific interrupt in the XIC pending register, mainly used for SW generating interrupt.
bool XIC_HasPendingIRQ (IRQn_Type IRQn)
check whether there are pending interrupt for specific IRQ
void XIC_ClearPendingIRQ (IRQn_Type IRQn)
Clears the pending bit of a device specific interrupt in the XIC pending register.
uint32_t XIC_LatchIRQ (XIC_TypeDef *xic)
Latch the pending interrupt status to the latch register and read out.
void XIC_SuppressOvfIRQ (IRQn_Type IRQn)
Suppress overflow IRQ.
void XIC_ClearAllPendingIRQ (XIC_TypeDef *xic)
Clears all pending bits of a XIC interrupt controller.
Description
Driver API for XIC(External Interrupt controller)
Macro Definition Documentation
NUM_XIC_MODULE
#define NUM_XIC_MODULE (3U)
number of XIC module
NUM_XIC0_INT
#define NUM_XIC0_INT (32U)
number of interrupts in XIC0
NUM_XIC1_INT
#define NUM_XIC1_INT (32U)
number of interrupts in XIC1
NUM_XIC2_INT
#define NUM_XIC2_INT (27U)
number of interrupts in XIC2
MAX_NUM_XIC_INT
#define MAX_NUM_XIC_INT (32U)
maximum number of interrupts in XIC
Typedef Documentation
ISRFunc_T
typedef void(* ISRFunc_T) (void)
ISR function type define
Function Documentation
IC_PowupInit()
void IC_PowupInit (void)
Initialize the interrupt controller, including HW configuration and ISR initialization, called when POR or wakeup from Hibernate, in which the SRAM contents have been lost.
Referenced by BSP_CommonInit(), and BSP_Init_SmallImg().
IC_PowupSlp1Init()
void IC_PowupSlp1Init (void)
for paging sleep1 init called when start sleep1 paging flow
Referenced by BSP_Init_Slp1Presync().
IC_Powoff()
void IC_Powoff (void)
DeInitialize the interrupt controller, including HW configuration and ISR initialization.
XIC_SetVector()
void XIC_SetVector (IRQn_Type IRQn, ISRFunc_T vector)
Sets an XIC interrupt vector in SRAM based interrupt vector table. Use this function to bind the XIC interrupt and application ISR.
Parameters
[in] IRQn Interrupt number
[in] vector Address of interrupt handler function
Note
The interrupt number must be positive
Referenced by GPR_rmiErrDetectInit().
XIC_EnableIRQ()
void XIC_EnableIRQ (IRQn_Type IRQn)
Enables a device specific interrupt in the XIC interrupt controller.
Parameters
[in] IRQn Interrupt number
Note
The interrupt number must be positive
XIC_DisableIRQ()
void XIC_DisableIRQ (IRQn_Type IRQn)
Disables a device specific interrupt in the XIC interrupt controller.
Parameters
[in] IRQn Interrupt number
Note
The interrupt number must be positive
XIC_BackupIRQSetting()
void XIC_BackupIRQSetting (uint32_t * mask, uint32_t * xic_clrovf)
backup the interrupt mask setting before sleep
Parameters
[out] mask[3] to store the irq mask
Note
XIC_RestoreIRQSetting()
void XIC_RestoreIRQSetting (uint32_t * mask, uint32_t * xic_clrovf)
restore the interrupt mask setting after sleep
Parameters
[in] mask[3] is the stored value before sleep
Note
XIC_SetPendingIRQ()
void XIC_SetPendingIRQ (IRQn_Type IRQn)
Sets the pending bit of a device specific interrupt in the XIC pending register, mainly used for SW generating interrupt.
Parameters
[in] IRQn Interrupt number
Note
The interrupt number must be positive
XIC_HasPendingIRQ()
bool XIC_HasPendingIRQ (IRQn_Type IRQn)
check whether there are pending interrupt for specific IRQ
Parameters
[in] IRQn Interrupt number
Note
The interrupt number must be positive
Referenced by pmuHasAtData().
XIC_ClearPendingIRQ()
void XIC_ClearPendingIRQ (IRQn_Type IRQn)
Clears the pending bit of a device specific interrupt in the XIC pending register.
Parameters
[in] IRQn Interrupt number
Note
The interrupt number must be positive
XIC_LatchIRQ()
uint32_t XIC_LatchIRQ (XIC_TypeDef * xic)
Latch the pending interrupt status to the latch register and read out.
Parameters
[in] xic Pointer to XIC instance
Returns
Interrupt status
XIC_SuppressOvfIRQ()
void XIC_SuppressOvfIRQ (IRQn_Type IRQn)
Suppress overflow IRQ.
Parameters
[in] IRQn Interrupt number
Note
The interrupt number must be positive
XIC_ClearAllPendingIRQ()
void XIC_ClearAllPendingIRQ (XIC_TypeDef * xic)
Clears all pending bits of a XIC interrupt controller.
Parameters
[in] xic Pointer to XIC instance