PAD Interface
PAD Interface
Driver API for PAD.
Data Structures
struct pad_config_t
PAD configuration structure.
Enumerations
enum pad_mux_t {
PAD_MuxAlt0 = 0U,
PAD_MuxAlt1 = 1U,
PAD_MuxAlt2 = 2U,
PAD_MuxAlt3 = 3U,
PAD_MuxAlt4 = 4U,
PAD_MuxAlt5 = 5U,
PAD_MuxAlt6 = 6U,
PAD_MuxAlt7 = 7U
}
PAD pin mux selection.
enum _pad_pull_up {
PAD_PullUpDisable = 0U,
PAD_PullUpEnable = 1U
}
Internal pull-up resistor configuration.
enum _pad_pull_down {
PAD_PullDownDisable = 0U,
PAD_PullDownEnable = 1U
}
Internal pull-down resistor configuration.
enum _pad_pull_sel {
PAD_PullAuto = 0U,
PAD_PullInternal = 1U
}
Pull feature selection.
enum _pad_input_buffer {
PAD_InputControlAuto = 0U,
PAD_InputControlSwOn = 1U
}
Input buffer enable/disable.
enum pad_pull_config_t {
PAD_InternalPullUp = 0U,
PAD_InternalPullDown = 1U,
PAD_AutoPull = 2U
}
Configures pull feature.
enum pad_drive_strength_t {
PAD_DriverStrengthLow = 0U,
PAD_DriverStrengthHigh = 1U
}
Drive strength configuration.
PAD Driver Initialization
void PAD_DriverInit (void)
Intialize PAD driver internal data, must be called before any other APIs.
void PAD_DriverDeInit (void)
Configuration
void PAD_GetDefaultConfig (pad_config_t *config)
Gets the PAD default configuartion This function sets the configuration structure to default values as below:
void PAD_SetPinConfig (uint32_t pin, const pad_config_t *config)
Sets the pad PCR register.
void PAD_SetPinMux (uint32_t pin, pad_mux_t mux)
Configures pin mux.
void PAD_SetPinPullConfig (uint32_t pin, pad_pull_config_t config)
Configures pin's pull feature.
Description
Driver API for PAD.
The PAD module provides support for signal muxing and eletrical properties control.
Data Structure Documentation
pad_config_t
struct pad_config_t
PAD configuration structure.
Data Fields
uint32_t __pad0__: 4
uint32_t mux: 3
Pad mux configuration
uint32_t __pad1__: 1
uint32_t pullUpEnable: 1
Enable pull-up
uint32_t pullDownEnable: 1
Enable pull-down
uint32_t pullSelect: 1
Pull select, external or internal control
uint32_t inputForceDisable: 1
Force to disable input or not, if true, input path is cut off, otherwise, it's controlled by inputControl bit
uint32_t __pad2__: 1
uint32_t inputControl: 1
Input enable, 'force' on or controlled by muxed alt function signal, i.e. I2C SCL
uint32_t __pad3__: 3
uint32_t driveStrength: 1
uint32_t __pad4__: 14
Enumeration Type Documentation
pad_mux_t
enum pad_mux_t
PAD pin mux selection.
Enumerator
PAD_MuxAlt0
Chip-specific
PAD_MuxAlt1
Chip-specific
PAD_MuxAlt2
Chip-specific
PAD_MuxAlt3
Chip-specific
PAD_MuxAlt4
Chip-specific
PAD_MuxAlt5
Chip-specific
PAD_MuxAlt6
Chip-specific
PAD_MuxAlt7
Chip-specific
_pad_pull_up
enum _pad_pull_up
Internal pull-up resistor configuration.
Enumerator
PAD_PullUpDisable
Internal pull-up resistor is disabled
PAD_PullUpEnable
Internal pull-up resistor is enabled
_pad_pull_down
enum _pad_pull_down
Internal pull-down resistor configuration.
Enumerator
PAD_PullDownDisable
Internal pull-down resistor is disabled
PAD_PullDownEnable
Internal pull-down resistor is enabled
_pad_pull_sel
enum _pad_pull_sel
Pull feature selection.
Enumerator
PAD_PullAuto
Pull up/down is controlled by muxed alt function
PAD_PullInternal
Use internal pull-up/down resistor
_pad_input_buffer
enum _pad_input_buffer
Input buffer enable/disable.
Enumerator
PAD_InputControlAuto
Input is controlled by muxed alt function signal, i.e. I2C SCL
PAD_InputControlSwOn
Input is forced enable
pad_pull_config_t
enum pad_pull_config_t
Configures pull feature.
Enumerator
PAD_InternalPullUp
select internal pull up
PAD_InternalPullDown
select internal pull down
PAD_AutoPull
Pull up/down is controlled by muxed alt function
pad_drive_strength_t
enum pad_drive_strength_t
Drive strength configuration.
Enumerator
PAD_DriverStrengthLow
Drive strength is low
PAD_DriverStrengthHigh
Drive strength is high
Function Documentation
PAD_DriverInit()
void PAD_DriverInit (void)
Intialize PAD driver internal data, must be called before any other APIs.
De-Intialize PAD driver, disable PAD clock and perform some clearups.
Referenced by BSP_CommonInit(), BSP_Init_Slp1Presync(), and BSP_Init_SmallImg().
PAD_DriverDeInit()
void PAD_DriverDeInit (void)
PAD_GetDefaultConfig()
void PAD_GetDefaultConfig (pad_config_t * config)
Gets the PAD default configuartion This function sets the configuration structure to default values as below:
config->mux = PAD_MuxAlt0;
config->inputControl = PAD_InputControlAuto;
config->inputForceDisable = 0;
config->pullSelect = PAD_PullAuto;
config->pullUpEnable = PAD_PullUpDisable;
config->pullDownEnable = PAD_PullDownDisable;
config->driveStrength = PAD_DriverStrengthHigh;
Parameters
config Pointer to PAD configuration structure
PAD_SetPinConfig()
void PAD_SetPinConfig (uint32_t pin, const pad_config_t * config)
Sets the pad PCR register.
Parameters
pin PAD pin number
config Pointer to PAD configuration structure
PAD_SetPinMux()
void PAD_SetPinMux (uint32_t pin, pad_mux_t mux)
Configures pin mux.
Parameters
pin PAD pin number
mux pin signal source selection
PAD_SetPinPullConfig()
void PAD_SetPinPullConfig (uint32_t pin, pad_pull_config_t config)
Configures pin's pull feature.
Parameters
pin PAD pin number
config PAD pin pull configuration