plat_config.c File Reference
plat_config.c File Reference
Macros
#define FS_PLAT_CONFIG_FILE_CURRENT_VERSION (1)
config file version
#define RAW_FLASH_PLAT_CONFIG_FILE_CURRENT_VERSION (0)
Functions
void BSP_LoadPlatConfigFromFs (void)
Load platform configuration from FS.
void BSP_SavePlatConfigToFs (void)
Save platform configuration into FS.
PLAT_CODE_IN_RAM uint32_t BSP_GetPlatConfigItemValue (plat_config_id_t id)
Get value of specific platform configuration item.
void BSP_SetPlatConfigItemValue (plat_config_id_t id, uint32_t value)
Set value of specific platform configuration item.
plat_config_fs_t * BSP_GetFsPlatConfig (void)
Get FS platform configuration variable pointer.
uint8_t BSP_QSPI_Erase_Safe (uint32_t SectorAddress, uint32_t Size)
uint8_t BSP_QSPI_Write_Safe (uint8_t *pData, uint32_t WriteAddr, uint32_t Size)
uint8_t FLASH_eraseSector (uint32_t BlockAddress)
uint8_t FLASH_write (uint8_t *pData, uint32_t WriteAddr, uint32_t Size)
UINT32 getOSState (void)
void BSP_SavePlatConfigToRawFlash (void)
Save platform configuration into raw flash.
void BSP_LoadPlatConfigFromRawFlash (void)
Load platform configuration from raw flash.
plat_config_raw_flash_t * BSP_GetRawFlashPlatConfig (void)
Get raw flash platform configuration variable pointer.
uint32_t BSP_GetFSAssertCount (void)
Fetch current 'fsAssertCount' value from PLAT_INFO region.
void BSP_SetFSAssertCount (uint32_t value)
Update 'fsAssertCount' value.
Variables
plat_config_raw_flash_t g_rawFlashPlatConfig
Macro Definition Documentation
FS_PLAT_CONFIG_FILE_CURRENT_VERSION
#define FS_PLAT_CONFIG_FILE_CURRENT_VERSION (1)
config file version
Note
when the order of struct plat_config_fs_t and plat_config_raw_flash_t field has changed, for example, from 1,2,3 to 1,3,2, update version to refresh flash, in other cases(add more fields or remove some fields from struct plat_config_fs_t), it's not a must to update
version update from 0 to 1: Add atPortFrameFormat config item
RAW_FLASH_PLAT_CONFIG_FILE_CURRENT_VERSION
#define RAW_FLASH_PLAT_CONFIG_FILE_CURRENT_VERSION (0)
Referenced by BSP_SavePlatConfigToRawFlash().
Function Documentation
BSP_LoadPlatConfigFromFs()
void BSP_LoadPlatConfigFromFs (void)
Load platform configuration from FS.
Returns
void
BSP_SavePlatConfigToFs()
void BSP_SavePlatConfigToFs (void)
Save platform configuration into FS.
Returns
void
BSP_GetPlatConfigItemValue()
PLAT_CODE_IN_RAM uint32_t BSP_GetPlatConfigItemValue (plat_config_id_t id)
Get value of specific platform configuration item.
Parameters
[in] id id of platform configuration item, plat_config_id_t
Returns
value of current configuration item
BSP_SetPlatConfigItemValue()
void BSP_SetPlatConfigItemValue (plat_config_id_t id, uint32_t value)
Set value of specific platform configuration item.
Parameters
[in] id id of platform configuration item, plat_config_id_t
[in] value value of configuration item to set
Returns
void
BSP_GetFsPlatConfig()
plat_config_fs_t* BSP_GetFsPlatConfig (void)
Get FS platform configuration variable pointer.
Returns
pointer to internal platform configuration loaded from FS
BSP_QSPI_Erase_Safe()
uint8_t BSP_QSPI_Erase_Safe (uint32_t SectorAddress, uint32_t Size)
Referenced by BSP_SavePlatConfigToRawFlash(), and BSP_SetFSAssertCount().
BSP_QSPI_Write_Safe()
uint8_t BSP_QSPI_Write_Safe (uint8_t * pData, uint32_t WriteAddr, uint32_t Size)
Referenced by BSP_SavePlatConfigToRawFlash(), and BSP_SetFSAssertCount().
FLASH_eraseSector()
uint8_t FLASH_eraseSector (uint32_t BlockAddress)
Referenced by BSP_SavePlatConfigToRawFlash().
FLASH_write()
uint8_t FLASH_write (uint8_t * pData, uint32_t WriteAddr, uint32_t Size)
Referenced by BSP_SavePlatConfigToRawFlash().
getOSState()
UINT32 getOSState (void)
Referenced by BSP_SavePlatConfigToRawFlash().
BSP_SavePlatConfigToRawFlash()
void BSP_SavePlatConfigToRawFlash (void)
Save platform configuration into raw flash.
Returns
void
BSP_LoadPlatConfigFromRawFlash()
void BSP_LoadPlatConfigFromRawFlash (void)
Load platform configuration from raw flash.
Returns
void
Referenced by ec_main().
BSP_GetRawFlashPlatConfig()
plat_config_raw_flash_t* BSP_GetRawFlashPlatConfig (void)
Get raw flash platform configuration variable pointer.
Returns
pointer to internal platform configuration loaded from raw flash
BSP_GetFSAssertCount()
uint32_t BSP_GetFSAssertCount (void)
Fetch current 'fsAssertCount' value from PLAT_INFO region.
Returns
current fsAssertCount value
BSP_SetFSAssertCount()
void BSP_SetFSAssertCount (uint32_t value)
Update 'fsAssertCount' value.
Parameters
[in] value new value assigned to 'fsAssertCount'
Returns
void
Note
Internal use only on FS assert occurs
Variable Documentation
g_rawFlashPlatConfig
plat_config_raw_flash_t g_rawFlashPlatConfig
Referenced by BSP_GetPlatConfigItemValue(), BSP_GetRawFlashPlatConfig(), BSP_SavePlatConfigToRawFlash(), and BSP_SetPlatConfigItemValue().